import type { Material } from './types'

export const MATERIALS: Material[] = [
  {
    id: 'carton-300',
    nameTh: 'กระดาษกล่องแป้ง 300 gsm',
    detail: 'กล่องเครื่องสำอาง · ยา/อาหารเสริม · ขนม',
    thickness: 0.4,
    foldable: true,
    process: 'ไดคัท + พับ + ทากาว',
    color: '#f0e9d8',
    roughness: 0.85,
  },
  {
    id: 'carton-400',
    nameTh: 'กระดาษกล่องแป้ง 400 gsm',
    detail: 'กล่องสินค้าน้ำหนักมาก · ของพรีเมียม · กล่องรองเท้า',
    thickness: 0.55,
    foldable: true,
    process: 'ไดคัท + พับ + ทากาว',
    color: '#ece4d0',
    roughness: 0.85,
  },
  {
    id: 'kraft-350',
    nameTh: 'กระดาษคราฟท์ 350 gsm',
    detail: 'แบรนด์อีโค่/ออร์แกนิก · ของฝากคราฟท์ · เบเกอรี่',
    thickness: 0.5,
    foldable: true,
    process: 'ไดคัท + พับ + ทากาว',
    color: '#b9905d',
    roughness: 0.95,
  },
  {
    id: 'corrugated-e',
    nameTh: 'ลูกฟูกลอน E',
    detail: 'กล่องรีเทลพิมพ์สวย · กล่องของขวัญ · สินค้ากันกระแทกบาง',
    thickness: 1.6,
    foldable: true,
    process: 'ไดคัท + พับ',
    color: '#c9a06a',
    roughness: 1,
  },
  {
    id: 'corrugated-b',
    nameTh: 'ลูกฟูกลอน B',
    detail: 'กล่องไปรษณีย์ · ขนส่ง/ลังสินค้า · ของหนัก',
    thickness: 3,
    foldable: true,
    process: 'ไดคัท + พับ',
    color: '#c39a63',
    roughness: 1,
  },
  {
    id: 'pet-sheet',
    nameTh: 'แผ่น PET ใส 0.3 มม.',
    detail: 'กล่องโชว์สินค้า · ของขวัญใส · เบเกอรี่/คัพเค้ก',
    thickness: 0.3,
    foldable: true,
    process: 'ไดคัท + รีดรอยพับ (crease) + พับ',
    color: '#bdd9e6',
    opacity: 0.35,
    roughness: 0.15,
  },
  {
    id: 'pet-bottle',
    nameTh: 'ขวด PET',
    detail: 'น้ำดื่ม · น้ำผลไม้/น้ำอัดลม · ซอส/เครื่องปรุง',
    thickness: 0.25,
    foldable: false,
    process: 'เป่าขึ้นรูป (blow molding)',
    color: '#9fc9dd',
    opacity: 0.5,
    roughness: 0.12,
    note: 'ขึ้นรูปด้วยการเป่า — blueprint ที่เห็นคือ dieline ของฉลากพันรอบขวด พร้อมส่งพิมพ์',
  },
  {
    id: 'glass',
    nameTh: 'แก้ว',
    detail: 'น้ำผึ้ง/แยม · เครื่องดื่มพรีเมียม · เทียนหอม/ครีม',
    thickness: 2,
    foldable: false,
    process: 'เป่า/หล่อขึ้นรูป',
    color: '#cfe6dd',
    opacity: 0.55,
    roughness: 0.08,
    note: 'ขึ้นรูปจากแม่พิมพ์ — blueprint ที่เห็นคือ dieline ของฉลากพันรอบโหล/ขวด พร้อมส่งพิมพ์',
  },
  {
    id: 'aluminum',
    nameTh: 'อะลูมิเนียม',
    detail: 'น้ำอัดลม/เบียร์ · น้ำผลไม้ · เครื่องดื่มชูกำลัง',
    thickness: 0.2,
    foldable: false,
    process: 'ดึงขึ้นรูป (draw & iron)',
    color: '#dfe3e7',
    roughness: 0.22,
    metalness: 0.9,
    note: 'ดึงขึ้นรูปจากแผ่น — blueprint ที่เห็นคือ dieline ของฉลาก/สติกเกอร์พันรอบกระป๋อง พร้อมส่งพิมพ์',
  },
  {
    id: 'pouch-foil',
    nameTh: 'ถุงฟอยล์ตั้งได้ (doypack)',
    detail: 'กาแฟ/ชา · ขนม/ของขบเคี้ยว · ผงชง/อาหารเสริม',
    thickness: 0.12,
    foldable: false,
    form: 'pouch',
    process: 'พิมพ์ + ลามิเนต + ซีลขอบขึ้นรูปถุง',
    color: '#e7e3d8',
    roughness: 0.32,
    metalness: 0.55,
    note: 'ถุงฟิล์มซีลขอบ — blueprint ที่เห็นคือแผ่นฟิล์มแบน (หน้า+หลัง+ก้น) พร้อมส่งพิมพ์',
  },
  {
    id: 'pouch-kraft',
    nameTh: 'ถุงคราฟท์ตั้งได้',
    detail: 'ชา/ธัญพืช · สินค้าออร์แกนิก · กาแฟสายอีโค่',
    thickness: 0.14,
    foldable: false,
    form: 'pouch',
    process: 'พิมพ์ + ลามิเนต + ซีลขอบขึ้นรูปถุง',
    color: '#c8a778',
    roughness: 0.85,
    note: 'ถุงฟิล์มซีลขอบ — blueprint ที่เห็นคือแผ่นฟิล์มแบน (หน้า+หลัง+ก้น) พร้อมส่งพิมพ์',
  },
  {
    id: 'tube-laminate',
    nameTh: 'หลอดครีม (laminate tube)',
    detail: 'ครีม/โลชั่น · ยาสีฟัน · เจลล้างหน้า/ยาทา',
    thickness: 0.3,
    foldable: false,
    form: 'tube',
    process: 'ขึ้นรูปหลอด + พิมพ์ตัวหลอด + ปิดท้ายซีล',
    color: '#ece7de',
    roughness: 0.28,
    note: 'หลอดบีบขึ้นรูป — blueprint ที่เห็นคือ dieline ของงานพิมพ์พันรอบตัวหลอด พร้อมส่งพิมพ์',
  },
  {
    id: 'sticker-vinyl',
    nameTh: 'สติกเกอร์ไวนิล',
    detail: 'ฉลากกันน้ำ · สติกเกอร์ขวด/แก้ว · โลโก้ติดสินค้า',
    thickness: 0.1,
    foldable: true,
    process: 'พิมพ์ + เคลือบ + ไดคัท',
    color: '#ffffff',
    roughness: 0.35,
    note: 'งานพิมพ์แบน + ไดคัทตามรูป — blueprint ที่เห็นคือเส้นตัดของสติกเกอร์ พร้อมส่งพิมพ์',
  },
  {
    id: 'sticker-pp',
    nameTh: 'สติกเกอร์ PP (ขาว)',
    detail: 'ฉลากขวดน้ำ/เครื่องสำอาง · ของเข้าตู้เย็น · สติกเกอร์แจก/ขาย',
    thickness: 0.08,
    foldable: true,
    process: 'พิมพ์ + ไดคัท',
    color: '#ffffff',
    roughness: 0.4,
    note: 'พลาสติก PP สีขาวทึบ กันน้ำ ทนกว่ากระดาษ — สีออกตรงกับจอที่สุดในกลุ่มสติกเกอร์',
  },
  {
    id: 'sticker-pp-clear',
    nameTh: 'สติกเกอร์ PP ใส',
    detail: 'ติดขวดแก้ว/กระจกให้เห็นพื้นผิว · ลายเส้นสีเข้ม',
    thickness: 0.08,
    foldable: true,
    process: 'พิมพ์ + ไดคัท',
    color: '#e8f0f4',
    roughness: 0.15,
    clear: true,
    note: 'ฟิล์มใส ไม่มีหมึกขาว — สีขาวในงานจะใส สีอ่อนจะจางจนแทบมองไม่เห็น เหมาะกับลายสีเข้ม',
  },
  {
    id: 'sticker-pp-clear-white',
    nameTh: 'สติกเกอร์ PP ใส รองขาว',
    detail: 'โลโก้บนขวดแก้ว · สติกเกอร์กระจกหน้าร้าน · ลายสีสดบนพื้นใส',
    thickness: 0.08,
    foldable: true,
    process: 'พิมพ์หมึกขาวรอง + พิมพ์สี + ไดคัท',
    color: '#e8f0f4',
    roughness: 0.15,
    clear: true,
    underbase: true,
    note: 'ฟิล์มใส + พิมพ์หมึกขาวรองใต้ลาย ลายทึบสด ส่วนอื่นยังใส — ไฟล์ส่งออกมีเลเยอร์ White ให้อัตโนมัติ',
  },
  {
    id: 'sticker-paper',
    nameTh: 'สติกเกอร์กระดาษ',
    detail: 'ฉลากทั่วไป · สติกเกอร์ราคาประหยัด · ฉลากกล่อง/ถุง',
    thickness: 0.12,
    foldable: true,
    process: 'พิมพ์ + ไดคัท',
    color: '#faf7ef',
    roughness: 0.6,
    note: 'งานพิมพ์แบน + ไดคัทตามรูป — blueprint ที่เห็นคือเส้นตัดของสติกเกอร์ พร้อมส่งพิมพ์',
  },
  {
    id: 'pouch-clear',
    nameTh: 'ถุงใสตั้งได้',
    detail: 'ลูกอม/ขนม · ของแห้ง/ถั่ว · สินค้าโชว์เนื้อใน',
    thickness: 0.1,
    foldable: false,
    form: 'pouch',
    process: 'พิมพ์ + ซีลขอบขึ้นรูปถุง',
    color: '#dbe7ec',
    opacity: 0.4,
    roughness: 0.2,
    note: 'ถุงฟิล์มซีลขอบ — blueprint ที่เห็นคือแผ่นฟิล์มแบน (หน้า+หลัง+ก้น) พร้อมส่งพิมพ์',
  },
]

export function getMaterial(id: string): Material {
  const m = MATERIALS.find((m) => m.id === id)
  if (!m) throw new Error(`unknown material: ${id}`)
  return m
}

// ชนิดงานที่ตัดสินใจ path (dieline/3D) จากวัสดุ: กล่องพับ / ภาชนะ revolve / ถุงฟิล์ม
export type PackKind = 'box' | 'vessel' | 'pouch'
export const packKind = (m: Material): PackKind =>
  m.foldable ? 'box' : m.form === 'pouch' ? 'pouch' : 'vessel'

// หลอดครีม = ภาชนะ revolve แบบพิเศษ (ฝาเกลียว + ปลายซีลแบน) — นำเสนอเป็นประเภทงานแยกใน UI
export const isTubeMat = (m: Material) => m.form === 'tube'
// สติกเกอร์ไดคัท = งานพิมพ์แบน — วัสดุ sticker-*
export const isStickerMat = (m: Material) => m.id.startsWith('sticker-')
